# Generated by Django 2.2.1 on 2019-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_summary',
            field=models.CharField(blank=True, help_text='Enter your Blog Summary', max_length=200, null=True, verbose_name='Blog Summary'),
        ),
    ]
