# Generated by Django 2.2.1 on 2019-06-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190604_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['blog_theme', 'blog_date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
