# Generated by Django 2.2.1 on 2019-06-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your First Name', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your Last Name', max_length=50, verbose_name='Last Name')),
                ('biography', models.TextField(help_text='Enter your Biography', verbose_name='Biography')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='Enter your Theme', max_length=50, verbose_name='Theme')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['theme'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_text', models.TextField(help_text='Enter your Blog Text', verbose_name='Blog Text')),
                ('blog_title', models.CharField(help_text='Enter your Blog Title', max_length=50, verbose_name='Blog Title')),
                ('blog_date', models.DateTimeField(auto_now=True, verbose_name='Blog Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('blog_theme', models.ForeignKey(help_text='Enter your Blog Theme', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Theme')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['blog_date'],
            },
        ),
    ]
