# Generated by Django 2.2.1 on 2019-06-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_summary',
            field=models.TextField(default=None, help_text='Enter your Blog Summary', verbose_name='Blog_Summary'),
            preserve_default=False,
        ),
    ]
